server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT   #匹配后提供服务的路由地址
        predicates:
          - Path=/payment/hystrix/ok/**   #断言,路径相匹配的进行路由
          - Between=2022-07-08T10:59:34.102+08:00[Asia/Shanghai] ,  2022-07-25T10:59:34.102+08:00[Asia/Shanghai]
        filters:
          # 在下游请求中添加 flag=1
          - AddRequestParameter=id,88
          # 自定义单一过滤器
          - Log=true,false,tanbiao
      - id: payment_routh2
        uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT
        predicates:
          - Path=/payment/hystrix/timeout/**   #断言,路径相匹配的进行路由
            #- Cookie=username,zhangshuai #并且Cookie是username=zhangshuai才能访问
            #- Header=X-Request-Id, \d+ #请求头中要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka/


