server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001  #eureka服务端的实例名字
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false          # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka/
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
  server:
    enable-self-preservation: true
